### ISSUE TITLE
Don't try to upload facts on puppet apply (no agent)

### ISSUE THREAD

**Issue by TJM** [albatrossflavour/puppet_os_patching#106]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.6
- Ruby: puppet ruby
- Distribution: CentOS 7
- Module version: v0.7.1

## How to reproduce (e.g Puppet code you use)

```
puppet module install albatrossflavour-os_patching
puppet apply -e 'include os_patching'
```

The reproduction of what I actually did was much grander, basically I test my puppet roles in vagrant, using puppet apply, and noticed big red errors (below) because it was trying to upload facts when it was not a puppet agent.

## What are you seeing

```
Error: Failed to open TCP connection to puppet:8140 (getaddrinfo: Name or service not known)
```

## What behaviour did you expect instead

It should somehow detect that it doesn't have a puppet master to upload to, and skip that step.

## Output log

```
[root@dyntest01 manifests]# rm -rf /var/cache/os_patching
[root@dyntest01 manifests]# puppet apply -e 'include os_patching'
Notice: Compiled catalog for dyntest01.vagrant.local in environment production in 0.14 seconds
Notice: /Stage[main]/Os_patching/File[/var/cache/os_patching]/ensure: created
Notice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Os_patching/File[/var/cache/os_patching/reboot_override]/ensure: defined content as '{md5}c21f969b5f03d33d43e04f8f136e7682'
Notice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]/returns: Notice: Uploading facts for 'dyntest01.vagrant.local' to: 'puppet'
Notice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]/returns: Warning: Accessing 'ca' as a setting is deprecated.
Notice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]/returns:    (location: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1165:in `issue_deprecation_warning')
Notice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]/returns: Error: Failed to open TCP connection to puppet:8140 (getaddrinfo: Name or service not known)
Notice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]/returns: Error: Try 'puppet help facts upload' for usage
Error: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: Failed to call refresh: '/opt/puppetlabs/bin/puppet facts upload' returned 1 instead of one of [0]
Error: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: '/opt/puppetlabs/bin/puppet facts upload' returned 1 instead of one of [0]
Notice: Applied catalog in 28.78 seconds
```

## Any additional information you'd like to impart

I like turtles!

**Comment by albatrossflavour** [comment]
You are a legend!

**Comment by TJM** [comment]
I was just making sure someone was paying attention

**Comment by albatrossflavour** [comment]
Hmmmm, I'm trying to figure out a reasonable way of detecting if the agent is running masterless.  Checking the `puppet_master_server` was my first guess, but it defaults to `puppet` if it's not set - which isn't going to help us.

I couldn't spot anything in the facts or in stdlib that might help detect if the catalog was locally compiled.

Any thoughts on how we could detect it?

**Comment by TJM** [comment]
The slack channel said something about prying around the Puppet namespace, but I am allocated to other projects right now :) 

> tvaughan [21 hours ago]
`/opt/puppetlabs/puppet/bin/gem install pry`


> tvaughan [21 hours ago]
Then just dump pry wherever you want on a `puppet apply` statement

**Comment by rnelson0** [comment]
I think looking at [server-side variables](https://puppet.com/docs/puppet/6.1/lang_facts_and_builtin_vars.html#puppet-master-variables) would be helpful. If `$servername` is defined, a master was used; if it is not defined, then apply was used. There are a number of other variables only provided by a server, if another looks more appropriate.

**Comment by albatrossflavour** [comment]
Nice idea.  I've been trying to keep away from having too much stuff 
dependant upon updating a profile to make it work properly, but this 
might be a case where it's worth while.

The other option I thought of was to have a parameter to the class to 
just disable the upload, with it being enabled by default.  @TJM would 
that work for you?

**Comment by albatrossflavour** [comment]
Branch feature/fact_upload has fixes for the stdlib issue and a new parameter to control the upload of facts (`$facts_upload = true`).

It has passed my testing, @TJM can you please take a look and let me know if this works for you?

I looked at the pry stuff but I think this way is a little more elegant.

**Comment by albatrossflavour** [comment]
```
[root@centos7 os_patching]# puppet apply -e "class { 'os_patching': fact_upload => false}"
Notice: Compiled catalog for centos7.lab.bandcamp.tv in environment production in 0.15 seconds
Notice: /Stage[main]/Os_patching/File[/var/cache/os_patching]/ensure: created
Notice: /Stage[main]/Os_patching/File[/var/cache/os_patching/reboot_override]/ensure: defined content as '{md5}c21f969b5f03d33d43e04f8f136e7682'
Notice: Applied catalog in 0.06 seconds
```

**Comment by TJM** [comment]
Well, I would much rather see something *automagic*, but this will work for now. We already have datacenter=vagrant, so we can just add it to hieradata.

**Comment by TJM** [comment]
In order to use this workaround, we added the following to our hieradata in `./data/datacenter/vagrant.yaml`:

```
#####
# os_patching: https://forge.puppet.com/albatrossflavour/os_patching
os_patching::fact_upload: false # We are not currently using puppet server (pupeptdb) in vagrant
```

Our `Vagrantfile` already had a fact defined to override the datacenter fact to be vagrant.

```ruby
    config.vm.provision :puppet do |puppet|
      # (other puppet related options)
      puppet.facter = {
         "datacenter"              => "vagrant",
         "role"                    => "base_linux",
       }
    end
```

**Comment by albatrossflavour** [comment]
Will look at some automagic options for the future, but at least  it's working for now.
