### ISSUE TITLE
Why stdlib 5.0.0?

### ISSUE THREAD

**Issue by TJM** [albatrossflavour/puppet_os_patching#107]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.6
- Ruby: puppet ruby
- Distribution: CentOS 7
- Module version: 0.6.4

## How to reproduce (e.g Puppet code you use)
N/A

## What are you seeing

Warning: ModuleLoader: module 'os_patching' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line notavailable)

## What behaviour did you expect instead

quietness

## Output log

see above

## Any additional information you'd like to impart

I noticed that the metadata.json is now requiring puppetlabs-stdlib 5.0.0. Why is that? Are we doing something that requires 5.0.0? I am not yet ready to upgrade due to some legacy/unsupported modules that are not yet ready for 5.0.0.

**Comment by albatrossflavour** [comment]
Fix staged ready for next release

**Comment by albatrossflavour** [comment]
Branch feature/fact_upload has a fix in for this

**Comment by TJM** [comment]
I confirm that with the PR mentioned above, I no longer receive warnings about module dependencies.

Thanks!

**Comment by albatrossflavour** [comment]
Thanks.  Closing.
