### ISSUE TITLE
create a dashboard by converting json to html

### ISSUE THREAD

**Issue by maxadamo** [albatrossflavour/puppet_os_patching#112]
I'd  like to see the json that I grab from puppetDB in a readable format: namely an HTML Dashboard

I made some attempt to convert to Json tree, but some work is required.

I started playing with a project called jqtree, I have seen json2table library as well, but I'd like to understand if there is an interest and we can make this work re-usable. 

my preferences goes for "json tree", because we may have hundreds of nodes, and it allows to expand and close the tree. 

maybe you have other ideas.

**Comment by albatrossflavour** [comment]
Hi.  Sorry it's taken a little while to respond to this issue.

I agree that having some kind of front end to puppet DB would be useful.  I'd suggest taking a look at [PuppetBoard](https://github.com/voxpupuli/puppetboard) as a starting point.

I don't think that adding a dashboard to the os_patchng module is the right solution.  The underlying data is exposed through the PuppetDB API and can be rendered/consumed by other applications.

**Comment by maxadamo** [comment]
I'm already a user of PuppetBoard. 
I can get your point, because the request is out of scope for this module, but the json is raw data...
