### ISSUE TITLE
Create the wiki and populate some how to guides

### ISSUE THREAD

**Issue by albatrossflavour** [albatrossflavour/puppet_os_patching#128]

**Comment by TJM** [comment]
Nice idea, maybe include some interesting queries... like a puppet query on all patch windows:

```
puppet query 'fact_contents[value, count()] { path = ["os_patching", "patch_window"] group by value }'
```

**Comment by albatrossflavour** [comment]
Wiki (https://github.com/albatrossflavour/puppet_os_patching/wiki/Background) and sample queries created.  More will be done as part of standard development.
