### ISSUE TITLE
puppetlabs/stdlib version 5.2.0

### ISSUE THREAD

**Issue by rfoster-ucd** [albatrossflavour/puppet_os_patching#129]
puppetlabs/stdlib version 5.2.0 is out, but dependency is capped at version 5.1.0

https://forge.puppet.com/puppetlabs/stdlib

**Comment by albatrossflavour** [comment]
@rfoster-ucd thanks for lodging this, really appreciate it.

I've got a fix going into development under PR #130 and will try to get a full release out to the forge later today.

**Comment by albatrossflavour** [comment]
Into dev for the next release.
