### ISSUE TITLE
Unable to run task os_patching::patch_server Windows 2012r2 with puppet enterprise agent 6.4.2

### ISSUE THREAD

**Issue by rigareau** [albatrossflavour/puppet_os_patching#133]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.4.2
- Ruby: 
- Distribution:
- Module version: 0.11.1

## How to reproduce (e.g Puppet code you use)
From the puppet master
puppet-task run os_patching::patch_server --nodes demowin2k12.my.domain

## What are you seeing
Starting job ...
Note: The task will run only on permitted nodes.
New job ID: 46
Nodes: 1

Started on demowin2k12.my.domain ...
Failed on demowin2k12.my.domain
  Error: Task exited 1:
    C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- win32/eventlog (LoadError)
        from C:/Program Files/Puppet Labs/Puppet/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from C:/ProgramData/PuppetLabs/pxp-agent/var/spool/46/temp_task_9f29-8932-45a1-7bd5/os_patching/tasks/patch_server.rb:6:in `initialize'
        from C:/ProgramData/PuppetLabs/pxp-agent/var/spool/46/temp_task_9f29-8932-45a1-7bd5/os_patching/tasks/patch_server.rb:63:in `new'
        from C:/ProgramData/PuppetLabs/pxp-agent/var/spool/46/temp_task_9f29-8932-45a1-7bd5/os_patching/tasks/patch_server.rb:63:in `<main>'

Job failed. 1 node failed, 0 nodes skipped, 0 nodes succeeded.
Duration: 20 sec

## What behaviour did you expect instead
Task completed successfully

**Comment by albatrossflavour** [comment]
@rigareau thanks so much for logging this.  @nathangiuliani and I looked into it and found that there might be some changes in the gems included with 6.4.2.  It's odd as event log is (well, **was**) required for the puppet agent.

Give us a couple of days to look into it.  As a workaround, you could try installing the event log gem in puppet's ruby env.

**Comment by rigareau** [comment]
I don't think that the proposed workaround is viable, at least for me...  I don't feel like installing this gem all over the place on all the Windows Puppet Agent...

**Comment by albatrossflavour** [comment]
I wouldn't disagree there, it was a suggestion for the "demo" box you had.  @nathangiuliani has confirmed that the gem is no longer included and we're looking at moving the windows logging code over to the standard ruby logger functions.

**Comment by rigareau** [comment]
Ah ok, make sense.

Thank you

**Comment by nathangiuliani** [comment]
Thanks for reporting this, @rigareau. I'll switch the code over to a file-based log rather than eventlog as the logger is part of ruby stdlib. I was surprised that puppet removed the eventlog gem from their package, but digging deeper it looks like they have written their own methods for eventlog entries so they weren't even using it.

**Comment by nathangiuliani** [comment]
initial fix in my fork - more testing required, but initial tests show it's working as expected. 

https://github.com/nathangiuliani/puppet_os_patching/tree/issue/133-eventlog-puppet-agent-6.4.2

**Comment by TraGicCode** [comment]
I also ran into this issue.  I'll give your branch a shot @nathangiuliani

**Comment by TraGicCode** [comment]
@nathangiuliani ,

You fix worked for me.

Thanks!
