### ISSUE TITLE
Every puppet run modifies os_patching_fact_generation.ps1 file

### ISSUE THREAD

**Issue by TraGicCode** [albatrossflavour/puppet_os_patching#135]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.4.2
- Ruby:
- Distribution:
- Module version: 0.11.1

## What are you seeing

Every puppet run i perform sees a change to the os_patching_fact_generation.ps1 file and puts the file back in the desired state.  Unfortunately every run ( even when done back to back ) the file somehow keeps getting out of sync and the module is attempting to sync it back.

## Any additional information you'd like to impart

![image](https://user-images.githubusercontent.com/6224270/58668689-49ec3900-82ff-11e9-90f5-b1dd0bba96ff.png)

**Comment by nathangiuliani** [comment]
@TraGicCode that's an interesting one. Haven't seen that anywhere in development or testing. Any idea what's changed in the file? Is there any more info in an agent debug log? Thanks.

**Comment by albatrossflavour** [comment]
I assume you don't have file bucket turned on, so we'll have to diagnose the old fashioned way.  Could you send us the output of `puppet agent -t` on the node, that way we can see the diff for the file.

**Comment by nathangiuliani** [comment]
Interestingly enough, the hash showing in your 'changed from' column is actually the correct hash.
if i manually edit os_patching_fact_generation.ps1 and then force a puppet agent run, i see the following:

content changed   '{md5}b2fd4502e4e7acf16f0adfb550aacb08' to   '{md5}3a34612bc3c54713a1c48c35a6dbc6c1' (corrective)

Also tried editing permissions to confirm that shows as a different correction, and it does.

If this is indeed happening on every run, it would be handy to get an exact copy of the os_patching_fact_generation.ps1 file from that node. Perhaps something like line endings is being changed - so the script will work, but is ending up with a different hash?

**Comment by TraGicCode** [comment]
Hey @nathangiuliani ,

Here is the file from the server


[os_patching_fact_generation.ps1.txt](https://github.com/albatrossflavour/puppet_os_patching/files/3239478/os_patching_fact_generation.ps1.txt)

**Comment by albatrossflavour** [comment]
The checksum on that file is the same as the one in the repo, which is what @nathangiuliani found.  Can you send the output from the `puppet agent -t` and/or check file bucket to see what the differences are?

**Comment by nathangiuliani** [comment]
That file binary compares 100% idendical to the file on any of my boxes tagged with the os_patching class.

Interesting to see that your 'changed from' MD5 matches what the file _should_ be.

If I edit the file on one of my boxes and force a puppet agent run, i see the following:

`Notice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]/content:

Notice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]/content: content changed '{md5}f6d5e70bd41178731d2f2ca0fe0cb9c9' to '{md5}3a34612bc3c54713a1c48c35a6dbc6c1'`

Would like to see your log and filebucket comaprison if you have it enabled.

**Comment by TraGicCode** [comment]
Here is the puppet agent -t.  I'm not sure this is enough logging to help out.

```
[0;32mInfo: Using configured environment 'production'[0m
[0;32mInfo: Retrieving pluginfacts[0m
[0;32mInfo: Retrieving plugin[0m
[0;32mInfo: Retrieving locales[0m
[0;32mInfo: Loading facts[0m
[0;32mInfo: Caching catalog for x00-02-dc.gccthd.com[0m
[0;32mInfo: Applying configuration version 'x00-01-xxx-production-7c38d6a1100'[0m
[mNotice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]/content: 
[0m
[mNotice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]/content: 
[0m
[mNotice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]/content: content changed '{md5}3a34612bc3c54713a1c48c35a6dbc6c1' to '{md5}9829d74c35c282cefc32cbdeaad70641' (corrective)[0m
[0;32mInfo: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]: Scheduling refresh of Exec[os_patching::exec::fact][0m
[0;32mInfo: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/os_patching_fact_generation.ps1]: Scheduling refresh of Exec[os_patching::exec::fact_upload][0m
[mNotice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: Triggered 'refresh' from 1 event[0m
[mNotice: /Stage[main]/Os_patching/Exec[os_patching::exec::fact]: Triggered 'refresh' from 1 event[0m
[mNotice: Applied catalog in 52.97 seconds[0m
```

**Comment by rnelson0** [comment]
Is it possible there’s file stream data, or some other metadata, that isn’t being overwritten? I would try deleting the file and running puppet twice to see if it recurs.

**Comment by albatrossflavour** [comment]
@TraGicCode is there any chance you could backup the file before the puppet run, do an agent run and send us both?  It's a very odd problem that we can't replicate at the moment.  Is it affecting multiple nodes and, if so, are they all the same windows version?

**Comment by TraGicCode** [comment]
Hey Guys,

Sorry i have had alot going on my side.

> is it possible there’s file stream data, or some other metadata, that isn’t being overwritten? I would try deleting the file and running puppet twice to see if it recurs.

Already tried this and it didn't work.

> is there any chance you could backup the file before the puppet run, do an agent run and send us both? It's a very odd problem that we can't replicate at the moment. Is it affecting multiple nodes and, if so, are they all the same windows version?

Sure but it might need to wait till next week

**Comment by albatrossflavour** [comment]
No rush, thanks for keeping us posted.

I've been trying to replicate it, no joy so far.

**Comment by TraGicCode** [comment]
We can close this for now.  I wont be able to get back to our azure bits for a while..
