### ISSUE TITLE
Version 0.11.1 of module cannot be installed on Windows (via Agent)

### ISSUE THREAD

**Issue by glennsarti** [albatrossflavour/puppet_os_patching#136]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any
- Ruby: N/A
- Distribution: N/A
- Module version: 0.11.1
- Windows 10 - 1903

## How to reproduce (e.g Puppet code you use)

On a Windows agent run `puppet module install albatrossflavour-os_patching --version 0.11.1` and it will fail to install

## What behaviour did you expect instead
Module should install

## Any additional information you'd like to impart

The tar.gz shows that there are files in the module that cannot exist on an NTFS volume.  These are in the `html/` directory and have a colon (`:`) in the name

Screenshot of the tar.gz
![image](https://user-images.githubusercontent.com/5819622/58843295-71972480-86a4-11e9-8708-9fe737db16f6.png)

Looking at the code, gitignore has this https://github.com/albatrossflavour/puppet_os_patching/blob/development/.gitignore#L27

but it's missing in pdkignore https://github.com/albatrossflavour/puppet_os_patching/blob/development/.pdkignore, so it looks like this was missed and `pdk build` is creating tarballs which cannot be extracted onto an NTFS filesystem.

**Comment by albatrossflavour** [comment]
Thanks @glennsarti, really appreciate the help.  I've excluded the files and will be generating a new package for the forge.
