### ISSUE TITLE
add flag to run "apt-get autoremove" after patching on ubuntu servers

### ISSUE THREAD

**Issue by jonasbartho** [albatrossflavour/puppet_os_patching#149]
**Is your feature request related to a problem? Please describe.**
Problem on Ubuntu is that is doesn't clean up old kernels automatically. Having a feature in this module to clean up old kernels would be super handy.

**Describe the solution you'd like**
A flag that can run "apt-get autoremove" after patching Ubuntu servers.

**Describe alternatives you've considered**
running "apt-get autoremove" through a cron job the day after patching.

**Additional context**
Be aware that apt-get autoremove only should run in 2 cases:
1) if no new kernel is installed within the patching round
2) if patching included a new kernel + needs a reboot, apt-autoremove should run after that reboot, not immediately after patching

!!! apt-get autoremove can remove the running kernel when the system is booted with an old kernel
!!! apt-get autoremove doesn't only remove old kernels, it also removes old dependencies that aren't necessary anymore

**Comment by albatrossflavour** [comment]
After talking to @jonasbartho we decided that an update to the manifest to allow an @reboot cron job which runs `apt-get -y autoremove`.  That code has been added in and is pending testing.

**Comment by albatrossflavour** [comment]
Complete
