### ISSUE TITLE
Reporting vulnerable package independently to package updates

### ISSUE THREAD

**Issue by smortex** [albatrossflavour/puppet_os_patching#155]
Hello, I am working on adding support for FreeBSD to this module.  So far so good, but I am concerned about a different behavior of the other platforms: FreeBSD does not have a direct way to say if a particular package update fix security issues are not, but we have an audit framework that can report vulnerable packages on a system (including packages which known vulnerabilities but without fixes).

Here is a sample report form the module on a FreeBSD node with all packages up-to-date but a version of go vulnerable (patched yesterday, but my repo does not have the fix yet):

```
{
  package_updates => [],
  package_update_count => 0,
  missing_update_kbs => [],
  security_package_updates => [
    "go-1.13,1"
  ],
  security_package_update_count => 1,
  blackouts => {},
  pinned_packages => [],
  last_run => {},
  patch_window => "",
  reboot_override => "default",
  reboots => {
    reboot_required => "",
    apps_needing_restart => {},
    app_restart_required => false
  },
  block_patching_on_warnings => "false",
  warnings => {
    version_specified_but_not_locked_packages => [
      "nats-pure"
    ]
  },
  blocked => false,
  blocked_reasons => []
}
```

The fact that this information appears as `security_package_updates` is a bit misleading, but restricting this list to vulnerable packages with updates available seems sub-optimal (we loose information about vulnerable packages without fixes, and nothing guarantees that the available update fix the issue).

A solution may be to add a `vulnerable_packages` key to list vulnerable packages.  Linux hosts could re-use the information from `security_package_updates`, and FreeBSD may just not provide `security_package_updates` first, and maybe parse the audit XML file to determine which updates fix vulnerabilities in the future.

What to you think?

**Comment by albatrossflavour** [comment]
I like the idea, but BSD is the only platform that this is relevant for.  The other platforms just report what is there that can be patched and (in some cases) if it's security related.

Can the audit tool report only items for which there is an unapplied patch in the repo?

**Comment by smortex** [comment]
I see.  If the goal is to provide a single interface, this extra information does not make sense as an output for the end user.

While `pkg audit` cannot be told to list only packages with updates available; filtering it's output to only show lines that match packages with updates looks doable and way easier than parsing the XML files that documents known vulnerabilities.

I'll try to provide an updated PR by next week.  Thanks!

**Comment by albatrossflavour** [comment]
Doesn't look like we'll be moving on this one yet.
