### ISSUE TITLE
Patching should probably report success if nothing was done

### ISSUE THREAD

**Issue by GiedriusS** [albatrossflavour/puppet_os_patching#157]
On CentOS 7.x I see this:
```
{"node":"1.2.3.4","target":"1.2.3.4","action":"task","object":"os_patching::patch_server","status":"failure","result":{"_error":{"msg":"Task exited : 1\nYum did not appear to run","kind":"os_patching/yum","d
etails":{"exitcode":"1","start_time":"2019-10-01T18:28:05+02:00","end_time":"2019-10-01T18:28:39+02:00"}}}}
```

This happens when the facts still haven't been updated in PuppetDB and we still try to run the patching task even if there are no patches to install. `puppet_os_patching` runs `yum update --security -y` but that, obviously, does not install anything and AFAICT that leads to no extra entry in the history that this task checks later on. This leads to that error message. It should probably report success instead.

**Comment by albatrossflavour** [comment]
Hi.  Thanks for reporting the issue, apologies for the delay in responding.

The message "yum did not appear to run" means that the tool things it SHOULD have run (as in there are patches to apply) but it couldn't find an entry in the yum history that matches what it was doing.  If you were running security only, it should only run the patching command if there are security updates showing as available.

Centos ***should*** never show as having security updates unless you've found some magic in your repo config that I'd love to see.

Could you send me the fact output from the node(s) in question?

**Comment by albatrossflavour** [comment]
Stale issue - feel free to reopen with the requested info if you're still seeing the issue.
