### ISSUE TITLE
lsbdistdescription missing on some system: installation is not forced

### ISSUE THREAD

**Issue by maxadamo** [albatrossflavour/puppet_os_patching#163]
hi @albatrossflavour 

first of all I'm not sure if this is a feature request, an issue for you, for me, an issue at all :question: 

The following issue has been reported on my module: https://github.com/maxadamo/patching_status/issues/1

1. The user experienced a crash, because `redhat-lsb-core` was not installed on his systems (I tried to uninstall `lsb-release` on Ubuntu and all the `lsb...` information are missing). 

2. From my side I can't do much (apart from making it very clear in the README that those packages need to be installed everywhere), because my module is not running on all the servers, but on one server only. 

3. On the other side I don't think an of OS report would make much (or any) sense, if you are not collecting at least the OS flavour! Am I right? You cannot pretend to store system information and you don't even know if it's Ubuntu or CentOS!!

3. yes, `lsbdistdescription` is a legacy fact :disappointed:, but when the `lsb...` package is missing even the modern facts `os['distro']['description']` do not work. I should migrate to modern fact, but it doesn't solve our problem. 

What is your opinion in this regard? 

Are you willing to force the installation?  
- on Ubuntu is called `lsb-release`. 
- on CentOS/RedHat is called `redhat-lsb-core`
- on Windows, not clear how this works. 

Or do you think: not my business if the user does not want to store this kind of information?

**Comment by albatrossflavour** [comment]
A standard Centos7 install doesn't include the `redhat-lsb-core` rpm and the `lsbdistdescription` doesn't resolve either.

Any of the legacy facts should be considered 'at risk'.

Without `redhat-lsb-core` the `os` fact looks like this:

```
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    config_mode => "enforcing",
    config_policy => "targeted",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}
```

with the `redhat-lsb-core` the `os` fact looks like this:

```
{
  architecture => "x86_64",
  distro => {
    codename => "Core",
    description => "CentOS Linux release 7.6.1810 (Core)",
    id => "CentOS",
    release => {
      full => "7.6.1810",
      major => "7",
      minor => "6"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    config_mode => "enforcing",
    config_policy => "targeted",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}
```

I would suggest updating the query to use `os.name` and `os.release.full`.

Managing `redhat-lsb-core` is out of scope for the patching module and there shouldn't be a requirement for it to be present for things to work correctly.

**Comment by maxadamo** [comment]
Why I didn't see that one? Thanks for your help :) 
P.s.: Facts are a mess and this is a fact. A lot of duplicate information, IP information flipping under certain circumstances... but that another story :)
