### ISSUE TITLE
Question: smart reboot does not reboot

### ISSUE THREAD

**Issue by elfranne** [albatrossflavour/puppet_os_patching#166]
Bug or feature ?
If no updates has been applied the code never reach the reboot logic.

If feature i ll gladly update the docs.

**Comment by albatrossflavour** [comment]
More of a feature.  Smart reboot should only reboot if patches were applied.  You can use `always` to reboot even if there were no patches applied.  The reboot logic is a gordian knot that I'm not massively happy with, but I can't think of a better way of handling it.  If you can, very happy to discuss.
