### ISSUE TITLE
Patching fails on Windows servers 

### ISSUE THREAD

**Issue by dannygoulder** [albatrossflavour/puppet_os_patching#169]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: PE 2018.1
- Ruby: 2.4.5p335
- Distribution: Windows
- Module version: 0.13.0

## How to reproduce (e.g Puppet code you use)
Classify the nodes, run the scheduled task and execute the task (I am using the PE GUI or puppet task CLI)

## What are you seeing
Error message:
```
  Error: Task exited : 11)
    The argument '/os_patching/files/os_patching_windows.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```

## What behaviour did you expect instead
Patching job to be run

## Output log
```
  Error: Task exited : 11)
    The argument '/os_patching/files/os_patching_windows.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
```
## Any additional information you'd like to impart
I've noted that the os_patching_windows.ps1 script doesn't actually get installed on the Windows server, and that there appears to be a private variable `_installdir` [here](https://github.com/albatrossflavour/puppet_os_patching/blob/5e4e7f6330b23e3535752fbe15bb6bd6ced8aa84/tasks/patch_server.rb#L563) which isn't set.

**Comment by albatrossflavour** [comment]
Hey @dannygoulder, really appreciate you logging the issue.  You didn’t mention what version of windows you’re running, any chance you can let me know?

Did you run the puppet agent against the node post classification and pre running the task?

**Comment by dannygoulder** [comment]
Hi @albatrossflavour thanks for the quick response!  Sorry for incomplete info.  I'm using Windows 2016 Server.  Yes, the agent was run after classification.  The scheduled task gets added correctly and the run is successful.  Not sure if it is important, but I am using Code Manager/r10k to add the module to the master, facts are sent by pluginsync and i have classified the node through the console for the time being.

**Comment by dannygoulder** [comment]
Hi the PR is there- I’ve added tests to get 100% resource coverage. Looks like one of the travis builds failed due to an infrastructure issue. Can we re-trigger the travis builds?

**Comment by dannygoulder** [comment]
So I kicked off the builds again.  Both Puppet5 runs failed, seemingly with a docker issue?

Do you have any thoughts?

**Comment by nathangiuliani** [comment]
Not something I've had experience with. @albatrossflavour, I remember you having issues when setting this up initially. Any ideas?

**Comment by albatrossflavour** [comment]
Not able to replicate
