### ISSUE TITLE
limit bandwith via yum/dnf and apt

### ISSUE THREAD

**Issue by jonasbartho** [albatrossflavour/puppet_os_patching#170]
Hi,

Feature request: Possibility/Module parameter to limit yum/dnf and apt bandwith when downloading packages from a given repository. This is especially useful in big enterprise environments with many clients.

Yum/dnf:
-> Ref. https://access.redhat.com/solutions/2965091
-> Short summary: adding the "throttle"-value in /etc/yum.conf to cap bandwith in KB/s + clean cache after change.
-> This applies to RHEL 6, 7 and 8
-> you already have a clean cache functionality in your module, which is perfect to combine with this.

Apt(less familiar with..)
-> Ref. https://askubuntu.com/questions/50402/how-to-limit-the-download-speed-of-apt
-> Short summary: create /etc/apt/apt.conf.d/75lowerspeed to cap bandwith in KB/s + clean cache after change.(=permanent throttling)

**Comment by albatrossflavour** [comment]
Hey @jonasbartho thanks for lodging this and apologies for the delay in responding.

I did consider using the throttling for updates, however I believe that the configuration of the update sources (apt/yum etc) should be handled by a different module.  The patching module is designed just to control the auditing, reporting and application of the patches.

Thanks again.
