### ISSUE TITLE
scheduled task to run os_patching_fact_generation.ps1 is hardcoded to every 12 hours

### ISSUE THREAD

**Issue by sirinek** [albatrossflavour/puppet_os_patching#174]
The documentation says that os_patching_fact_generation.ps1 is run every hour by default, but it is hardcoded to 720 minutes in the code. Can this be made configurable?

**Comment by albatrossflavour** [comment]
Good idea, I'll add this in an upcoming release

**Comment by albatrossflavour** [comment]
Enhancement merged into development with #197 and will be released as part of 0.16.0
