### ISSUE TITLE
Run os_patching without PMS (just with puppet apply)

### ISSUE THREAD

**Issue by klacol** [albatrossflavour/puppet_os_patching#182]
Hi, I am a newbie to puppet. We have a serverless environment. But on the hosts, we can run this command:

```
puppet module install albatrossflavour-os_patching --version 0.13.0
puppet apply my_puppet_class.pp --verbose --debug --detailed-exitcodes
```

The follwing code runs the facter and gives me alle the facts, inluding the missing KB's:
```
class my_puppet_class{
....
}
include os_patching
include my_puppet_class
```

But it does not install the missing KB's.  In the log I see this:

> Debug: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]: Nothing to manage: no ensure and the resource doesn't exist
> Debug: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/pre_patching_command]: Nothing to manage: no ensure and the resource doesn't exist
> Debug: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/block_patching_on_warnings]: Nothing to manage: no ensure and the resource doesn't exist
> Debug: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/blackout_windows]: Nothing to manage: no ensure and the resource doesn't exist
> Debug: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: '"C:/Program Files/Puppet Labs/Puppet/bin/puppet.bat" facts upload' won't be executed because of failed check 'refreshonly'
> Debug: /Stage[main]/Os_patching/Exec[os_patching::exec::fact]: 'powershell -executionpolicy remotesigned -file C:/ProgramData/os_patching/os_patching_fact_generation.ps1' won't be executed because of failed check 'refreshonly'

What am I doing wrong? Appreciate your help, thanks.

**Comment by albatrossflavour** [comment]
Hmmm, I've not tried running it serverless but I'll see if I can help.

Has the puppet apply run created `C:/ProgramData/os_patching/` and, if so, what files are in there?

**Comment by albatrossflavour** [comment]
I've checked that we can run all of the patching workflows using serverless (except triggering a task over PXP).

If you're still having issues, let me know and we'll dig into it.
