### ISSUE TITLE
Locked Log file on Windows

### ISSUE THREAD

**Issue by rychannel** [albatrossflavour/puppet_os_patching#186]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: PE 2019.8.0 / 6.16.0
- Ruby:
- Distribution: Windows 2008 R2
- Module version: 0.13

## How to reproduce (e.g Puppet code you use)
Run the task on servers that have patches.

## What are you seeing
When I run the patch task on a server I get the following error:
Error: Task exited : 2
Add-LogEntry : Exception caught: The process cannot access the file 
'C:\ProgramData\os_patching\os_patching_task.log' because it is being used by 
another process. At C:\ProgramData\PuppetLabs\pxp-agent\var\spool\2041\temp_tas
k_dbff-03b7-15f1-2826\os_patching\files\os_patching_windows.ps1:364 char:14

It's even odder because when it fires that error, it still puts that error it in that log

## What behaviour did you expect instead
Patch
## Output log
# Logfile created on 2020-08-05 07:51:08 -0500 by logger.rb/61378
I, [2020-08-05T07:51:08.112088 #13032]  INFO -- : os_patching run started
D, [2020-08-05T07:51:08.112088 #13032] DEBUG -- : Running os_patching fact refresh
D, [2020-08-05T07:51:08.112088 #13032] DEBUG -- : Gathering facts
I, [2020-08-05T07:52:15.911427 #13032]  INFO -- : Reboot after patching set to smart
I, [2020-08-05T07:52:15.911427 #13032]  INFO -- : Apply only security patches set to false
I, [2020-08-05T07:52:15.911427 #13032]  INFO -- : Running patching powershell script
E, [2020-08-05T07:53:58.172049 #13032] ERROR -- : ERROR : os_patching/win : 2 : Add-LogEntry : Exception caught: The process cannot access the file 
'C:\ProgramData\os_patching\os_patching_task.log' because it is being used by 
another process. At C:\ProgramData\PuppetLabs\pxp-agent\var\spool\2041\temp_tas
k_dbff-03b7-15f1-2826\os_patching\files\os_patching_windows.ps1:364 char:14
+         $_ | Remove-Item -Force -Confirm:$false
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
At C:\ProgramData\PuppetLabs\pxp-agent\var\spool\2041\temp_task_dbff-03b7-15f1-
2826\os_patching\files\os_patching_windows.ps1:804 char:5
+     Add-LogEntry ("Exception caught: {0} {1} " -f $_.exception.Messag ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Add-LogEntry

**Comment by albatrossflavour** [comment]
This should solve the locking issue.  Will be released with 0.16.0
