### ISSUE TITLE
long usernames in `yum history` cause 'yum did not appear to run'

### ISSUE THREAD

**Issue by sharumpe** [albatrossflavour/puppet_os_patching#192]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.22
- Ruby: 2.4.10p364
- Distribution: CentOS 7.9.2009
- Module version: 0.13.0

## How to reproduce (e.g Puppet code you use)

Run the `os_patching::patch_server` task (via sudo) as a user with a name that is too long for `yum history` to comfortably display.  I am running the bolt task from my desktop, and the task is executing on a remote CentOS 7 host.

## What are you seeing

When `yum history` is run, if the user's name in the "Login user" field is too long, that tool adds `...`, which isn't parsed by the regex on line 480.  It continues on to find the first line that does not contain those characters.  This results in the tool reporting 'yum did not appear to run' even though yum may have successfully updated the packages.

## What behaviour did you expect instead

Don't worry about the username, though TBF this is a weird edge case.

## Any additional information you'd like to impart

I've got a two-character fix that simply allows for the `.` character in that field.  I'm reporting this so that there's an issue to attach a future pull request to.  :)

**Comment by sharumpe** [comment]
I will submit a PR later today.  The change is just a couple of characters in the regex on line 480.

**Comment by albatrossflavour** [comment]
Thanks.  I've got a few issues and PRs to review.  I'll try and get onto that in the next couple of days, but really appreciate the PR.

**Comment by sharumpe** [comment]
> Thanks. I've got a few issues and PRs to review. I'll try and get onto that in the next couple of days, but really appreciate the PR.

Alright I've created the PR -- hopefully that's done the right way.  :)

**Comment by albatrossflavour** [comment]
Fixed in #192, merged into development ready for the 0.15.0 release
