### ISSUE TITLE
Fact generation on RHEL incorrectly indicating no PKGS for update

### ISSUE THREAD

**Issue by bzilla** [albatrossflavour/puppet_os_patching#212]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.24
- Ruby: 2.0.0.648-36
- Distribution: RHEL 7.9
- Module version: 0.17.0

## How to reproduce (e.g Puppet code you use)
With packages available via yum repos, os_patching_fact_generation.sh is creating an empty package_updates file.

## What are you seeing
The repos do have packages available for update:
root# yum check-update

openssl.x86_64                     1:1.0.2k-24.el7_9                MY-rhel7-updates
openssl-devel.x86_64               1:1.0.2k-24.el7_9                MY-rhel7-updates
openssl-libs.x86_64                1:1.0.2k-24.el7_9                MY-rhel7-updates

But line 38 in os_patching_fact_generation.sh is producing an empty PKGS variable:
root# yum -q check-update 2>/dev/null| egrep -v "^[Ss]ecurity:" |  egrep -i '^[[:alnum:]_-]+\.[[:alnum:]_-]+[[:space:]]+[[:alnum:]_.-]+[[:space:]]+[A-Za-z0-9_.-]+[[:space:]]*$' | awk '/^[[:alnum:]]/ {print $1}'
root#

The colon in the package version column is triggering the regex to exclude it. For example, If I test with a text file, "foo.txt":
-----
Security: kernel-3.14.6-200.fc20.x86_64 is an installed security update
Security: kernel-3.14.2-200.fc20.x86_64 is the currently running version
openssl.x86_64                     1:1.0.2k-24.el7_9                MY-rhel7-updates
openssl-devel.x86_64               1:1.0.2k-24.el7_9                MY-rhel7-updates
openssl-libs.x86_64                1:1.0.2k-24.el7_9                MY-rhel7-updates
-----
root# cat foo.txt | egrep -v "^[Ss]ecurity:" |  egrep -i '^[[:alnum:]_-]+\.[[:alnum:]_-]+[[:space:]]+[[:alnum:]_.-]+[[:space:]]+[A-Za-z0-9_.-]+[[:space:]]*$' | awk '/^[[:alnum:]]/ {print $1}'
root#

If I delete that colon in the version, changing "1:1" to "11" then I get the expected output.

If I greatly simplify this, I also get what's expected:
root# cat foo.txt | egrep -v "^[Ss]ecurity:" | awk '/^[[:alnum:]]/ {print $1}'
openssl.x86_64
openssl-devel.x86_64
openssl-libs.x86_64
root#

## What behaviour did you expect instead
I expect all available packages for update to be populated in the package_updates file.

**Comment by cosmocaan** [comment]
@albatrossflavour Any word on when this PR can be merged?  We are currently having to maintain a local copy and would like to get back to using the forge module.  Thanks

**Comment by albatrossflavour** [comment]
Merged under #216 thanks @prolixalias
