### ISSUE TITLE
Could not initialize global default settings:

### ISSUE THREAD

**Issue by trondk** [albatrossflavour/puppet_os_patching#213]
Hi im getting this error when i run the patch.

 
Task exited : 1
  Error: Could not initialize global default settings: libfacter was not found. Please make sure it was installed to the expected location.     

i cant seem to find where the problem is.
it is on a windows 2012, with puppet6 and a 0.17 release of os_patching

**Comment by albatrossflavour** [comment]
Hi.  Sounds like you're running this on puppet open source?  I've not tried that in a while but I don't think it works.  Happy to take a look with you and see if there is anything we can tweak to get it going.

**Comment by albatrossflavour** [comment]
Closing due to lack of follow up
