### ISSUE TITLE
stdlib 9.x.x compat

### ISSUE THREAD

**Issue by jcpunk** [albatrossflavour/puppet_os_patching#227]
**Is your feature request related to a problem? Please describe.**
With the new release of stdlib 9.x, the module dependencies should be updated

**Describe the solution you'd like**
Compatibility with stdlib 9.x

**Describe alternatives you've considered**
Staying locked at an older version

**Additional context**
https://forge.puppet.com/modules/puppetlabs/stdlib/changelog

**Comment by albatrossflavour** [comment]
I'll have to do some work on figuring this out, so many of the modules I'm using don't work with stdlib 9.  I'll have to cut a new control repo to do some testing on it.  Give me a week or two.
