### ISSUE TITLE
Locked, Exiting - Need trap(s) if we have a lockfile (/usr/local/bin/os_patching_fact_generation.sh)

### ISSUE THREAD

**Issue by TJM** [albatrossflavour/puppet_os_patching#42]
The shell script `/usr/local/bin/os_patching_fact_generation.sh` has a lock file, which is fine, but it needs to have `trap` statements to "cleanly" exit if, for example, the machine is rebooted while it happens to be running.

https://stackoverflow.com/questions/1715137/what-is-the-best-way-to-ensure-only-one-instance-of-a-bash-script-is-running

maybe something like:

```bash
trap "rm -f $LOCKFILE; exit" 0 2 3 15
```

added right near the top somewhere?

**Comment by albatrossflavour** [comment]
Thanks @TJM 

Addressed in [development](
https://github.com/albatrossflavour/puppet_os_patching/commit/2f29c83f8ac55b7386e9052d56bf7a4d6395740)
