### ISSUE TITLE
stack trace when task run before setup complete

### ISSUE THREAD

**Issue by GeoffWilliams** [albatrossflavour/puppet_os_patching#52]
**Overview**
If user runs task without setting up system, get a scary looking stack-trace

**Expected result**
System requires setup before task is first run - tell user

**Actual result**
Stack trace:

Error: Task exited 1:
/opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - /usr/local/bin/os_patching_fact_generation.sh (Errno::ENOENT)
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:95:in `popen3'
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/open3.rb:258:in `capture3'
	from /opt/puppetlabs/pxp-agent/tasks-cache/752f2408d34de6fd1c8a9caa64e050747a50c2af0b77a0957cdb4d8653e20cab/patch_server.rb:161:in `<main>'

**Workaround**
`include os_patching` on nodes first

**Comment by albatrossflavour** [comment]
Thanks Geoff, merged.
