### ISSUE TITLE
[bug] invalid times parsed from blackouts file silently ignored

### ISSUE THREAD

**Issue by GeoffWilliams** [albatrossflavour/puppet_os_patching#67]
The data in the file should always be valid but it may not be - devise a way to fix this and "stop the production line" if detected

**Comment by albatrossflavour** [comment]
We can use the 'warnings' hash in the fact and set a blocker if the syntax is incorrect. I'll take this one.

**Comment by albatrossflavour** [comment]
See comments on #69 for progress - being tracked in branch https://github.com/albatrossflavour/puppet_os_patching/tree/feature/data_parser

**Comment by albatrossflavour** [comment]
Fixed in #76
