### ISSUE TITLE
[enhancement] don't call facter from puppet

### ISSUE THREAD

**Issue by GeoffWilliams** [albatrossflavour/puppet_os_patching#68]
Calling facter from puppet is slow and takes several seconds. recommend moving the code in the custom fact that does reading to a shared library and just invoke it - this will save seconds

**Comment by TJM** [comment]
I think this can be closed per #95 too.

**Comment by maxadamo** [comment]
any idea if this one will be implemented? It will also solve #190 
it stopped working with puppet 7 and `facter -p puppet_vardir` does not work any longer.

**Comment by GeoffWilliams** [comment]
@albatrossflavour

**Comment by albatrossflavour** [comment]
Going to be addressed as part of the rework for puppet 7
