### ISSUE TITLE
[enhancement] consider validating incoming ISO-8601 timestamps for validity

### ISSUE THREAD

**Issue by GeoffWilliams** [albatrossflavour/puppet_os_patching#69]
allows `+1000`

**Comment by GeoffWilliams** [comment]
Long term fix might be: https://tickets.puppetlabs.com/browse/PUP-5871

**Comment by GeoffWilliams** [comment]
Actually.. just does a basic check and doesn't validate the timestamp right now

**Comment by albatrossflavour** [comment]
https://github.com/albatrossflavour/puppet_os_patching/tree/feature/data_parser is doing the parsing and validation now.  However the date command used in the acceptance testing ( `date --iso-8601=seconds --date  "09:00 tomorrow"`) outputs without the final colon in the offset.  Was going to dig into it tonight but even I'm not sad enough to read the ISO specs on a Sunday evening of a long weekend.

**Comment by albatrossflavour** [comment]
Fixed in #76 for certain values of "standard"
