### ISSUE TITLE
os_patching fact

### ISSUE THREAD

**Issue by TJM** [albatrossflavour/puppet_os_patching#73]
Should we consider making the os_patching fact be an "external fact?" For example, it could be a "yaml" file in facts.d, generated by the os_patching_fact_generation process. I am not sure what value there is in storing a bunch of cache files, then "assembling" them at puppet run time when you could just put them into "facts.d" as a yaml file when gathering the data in the first place. 

Whether or not we switch over to using facts.d, it might be a "good idea" to have a "last_updated" datestamp in the fact. The data for the fact is generated by an "external" process, that could potentially be failing (i.e. after a recent update, we had duplicate "cr" repos). The fact will not be aware of this failure, and will continue to report the last generated value, leading to confusion. 

~tommy

**Comment by albatrossflavour** [comment]
The fact was (in previous versions) just a yaml file.  As the split for different OS flavours matured it seemed easier to have a data generation layer (the cron job) and a presentation layer (the fact).

The current fact does have a number of warnings built in to show if things haven't been updated, though it's currently hard coded but that could easily change.

I don't have an issue with putting a timestamp entry into the fact to show the update time for each entry.  What do you think?

**Comment by TJM** [comment]
Hmm, I was thinking making the data gathering process output structured data in the format facter wants it would make it easier (less code). You wouldn't need to worry about finding a secure/safe place to store cache data on each OS, because you would just be writing it to the fact.d directory. Additionally, you just have the osfamily stuff (i.e. where to store the facts) in the (already) osfamily-specific data gathering script.  On the Linux side you may want to call the ruby script directly from the cron job, as opposed to trying to generate json or yaml from a shell script. On the windows side, you could just output a os_patching.json, since powershell seems to have json built in (just make sure you use the .NET file writer so you don't get a BOM :) )

However, in the long run, its just an implementation detail. It is not causing me any specific pain. Just a random thought I had :)

Does a timestamp make sense for each entry or just for the overall fact? I am not sure. Is it possible for one part to succeed while the other part fails? Maybe patching data vs reboot/restart data?

~tommy

**Comment by albatrossflavour** [comment]
I do see your point and I don’t have a really strong opinion on it 
either way now that I’ve got the structure of the fact sorted.  
Previously it was a shell script which was evolving and, as your pointed 
out, writing out json as shell was … interesting.

I’ll put it on the back burner for now but will think about it when 
doing the work on the windows branch to see if that might make life 
easier.

**Comment by albatrossflavour** [comment]
Looking at the different code bases, I'm more inclined to keep it the way it is at the moment.  Each generator script just lays down the cache data, then we have a single presentation layer script which outputs things the way we want it.

It's already saved a lot of duplicate work by having things set up this way.

I'll keep it in mind for how we COULD do things in the future but right now we'll stick as is.

**Comment by TJM** [comment]
All good with me, just a random thought I had :).
