### ISSUE TITLE
manage yum-utils?

### ISSUE THREAD

**Issue by TJM** [albatrossflavour/puppet_os_patching#74]
Since this process seems to depend on the `needs-restarting` provided by `yum-utils` rpm, shouldn't we be managing (at least optionally) the yum-utils package as well?

**Comment by albatrossflavour** [comment]
Good idea.  I've added it until https://github.com/albatrossflavour/puppet_os_patching/commit/b4d3f82f7c769b6071b999eafb266e711ebcea02
